////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#examples_finance]
= Financial Examples
:idprefix: financial_examples_

[#examples_money_parsing]
.This example demonstrates the numerical differences between parsing of monetary values between using `decimal32_t` and `float`
====
[source, c++]
----
include::example$numerical_parsing.cpp[]
----

.Expected Outcome
....
Number of data points: 252
    Sum from MS Excel: 52151.99
Sum using decimal32_t: 52151.99
      Sum using float: 52151.96
....
====

== Simple Moving Average

In the examples folder there is a file named `moving_average.cpp`.
This example shows how to parse historical stock data from a file and use it.
This serves as a framework for other calculations for securities.

== Currency Conversion
In the examples folder there is a file named `currency_conversion.cpp`.
This example shows how to simply convert currencies based off a given exchange rate.

[#examples_boost_math]
== Boost.Math Integration

=== Bollinger Bands

In the examples folder there is a file named `statistics.cpp`.
This example demonstrates how to parse a file, and then leverage Boost.Math to compute statistics of that data set culminating with the values of the Bollinger Bands.
This example could be extended with the simple moving average to create full bands based on the period of the moving average you would like.
